### PR TITLE
Add the test format2 utility in the public package.

### PR DESCRIPTION
**Pull request by Natim**
Because it is as useful as ``format`` itself.

I copy pasted it from the tests in my project and I though maybe it was best to expose it directly as a public functionality.

### CODE REVIEW

**Comment by basti1302** [comment]
Hi there! Thanks for the PR! <3

Honestly, I'm not entirely sure how I feel about this change. I guess I would prefer to only have *one* function that does not accept settings and uses sensible defaults. Are the IEC units actually that common? I have never used them before and only included them because one of the JS modules on npm I used as an inspiration mentioned them. Plus, if you have the need for formatting with IEC, you could always put `format2` somewhere in your code right and use it, right?

Do you have any convincing arguments for adding that function? (Even if you have, I definitely do not like the name, maybe formatBase2 would be a little better).

Finally, don't bother with fixing Travis. The code you added surely does not break any tests. The reason Travis fails is that a new version of https://www.npmjs.com/package/elm-test (the node-elm-test-runner) has been published which has breaking changes but unfortunately I did not specify a version in .travis.yml. I'll take care of this sooner or later.

**Comment by basti1302** [comment]
FWIW, Travis if happy again with the current master - I updated to the latest elm-test and node-test-runner, fixed .travis.yml accordingly and locked all versions.

**Comment by Natim** [comment]
> if you have the need for formatting with IEC, you could always put format2 somewhere in your code right and use it, right?

https://github.com/mozilla-services/buildhub/pull/74/files#diff-d7633e937f064e11207678188c49029aR13

Yes it is exactly what I did, but since you were using this function in the test already and that I was just going to copy/paste it into my code, I guess it was a solid argument for me that the function was useful.

I personally find it much more accurate to use MiB that MB but I guess it is a matter of taste.

The function is 2 lines of code in your lib and it simplifies greatly my code:

From:
```elm
import Filesize exposing (formatWith, defaultSettings, Units(..))


formatBase2 : Int -> String
formatBase2 =
    formatWith { defaultSettings | units = Base2 }
```

To:
```elm
import Filesize exposing (formatBase2)
```

Because the function already exists in the tests, it doesn't add anycode to maintain on your side so I guess I don't see why you wouldn't like to add it.

**Comment by basti1302** [comment]
I still feel somewhat ambiguos, but hey, so what, let's merge this.

**Comment by basti1302** [comment]
This has landed in 1.1.0

**Comment by Natim** [comment]
Thanks :)

**Pull request merged**
